name: Datadog Vulnerability Analysis with Snyk
description: |-
  Compute the dependency graph and upload it to Datadog.

inputs:
  build-file:
    description: |-
      The file that Snyk should inspect for package information.
    required: true
  service:
    description: |-
      The service name.
    required: true
  version:
    description: |-
      The version of the application.
    required: true
  datadog-api-key:
    description: |-
      The Datadog API key. A 32-character hexadecimal string. This key is created by your Datadog
      organization and should be stored as a Github secret.
    required: true
  datadog-app-key:
    description: |-
      The Datadog Application Key. A 40-character hexadecimal string. This key is created by your Datadog
      organization and should be stored as a Github secret.
    required: true
  snyk-token:
    description: |-
      The Snyk token used to run the `snyk test` command. This key is created from your Snyk account and
      should be stored as a Github secret.
    required: true
  site:
    description: |-
      The Datadog site, set to 'datadoghq.com' by default. Needs to be set to 'datadoghq.eu' for Datadog EU users.
    required: false
    default: datadoghq.com

runs:
  using: "composite"
  steps:
  - name: Install Snyk CLI tools
    run: npm install -g snyk
    shell: bash
  - name: Install Datadog-ci
    run: npm install -g --save-dev @datadog/datadog-ci
    shell: bash
  - name: Compute dependency graph
    run: ${{ github.action_path }}/snyk-test.sh "${{ inputs.build-file }}"
    shell: bash
    env:
      SNYK_TOKEN: ${{ inputs.snyk-token }}
  - name: Compact dependency graph
    run: |
      echo "Compacting dep graph"
      cat deps.json | jq -c '.' > deps2.json
      mv deps2.json deps.json
    shell: bash
  - name: Upload dependency graph
    run: datadog-ci dependencies upload ./deps.json --source snyk --service ${{ inputs.service }} --release-version ${{ inputs.version }}
    shell: bash
    env:
      DATADOG_API_KEY: ${{ inputs.datadog-api-key }}
      DATADOG_APP_KEY: ${{ inputs.datadog-app-key }}
      DATADOG_SITE: ${{ inputs.site }}
