name: Datadog Vulnerability Analysis with Snyk
description: |-
  Upload the dependency graph to Datadog.

inputs:
  service:
    description: |-
      The service name.
    required: true
  version:
    description: |-
      The version of the application.
    required: true
  site:
    description: |-
      The Datadog site, set to 'datadoghq.com' by default. Needs to be set to 'datadoghq.eu' for Datadog EU users.
    required: false
    default: datadoghq.com

runs:
  using: "composite"
  steps:
  - name: Install Snyk CLI tools
    run: npm install -g snyk
    shell: bash
  - name: Install Datadog-ci
    run: npm install -g --save-dev @datadog/datadog-ci
    shell: bash
  # TODO: Analyse snyk.json file to check the content is valid and report errors to the user
  - name: Compress dependency graph
    run: |
      echo "Compacting dep graph"
      cat snyk.json | jq -c '.' > snyk_tmp.json
      mv snyk_tmp.json snyk.json
    shell: bash
  - name: Upload dependency graph
    run: datadog-ci dependencies upload ./snyk.json --source snyk --service ${{ inputs.service }} --release-version ${{ inputs.version }}
    shell: bash
    env:
      DATADOG_SITE: ${{ inputs.site }}
