name: Datadog Vulnerability Analysis with Snyk
description: TODO

inputs:
  file:
    description: |-
      The file that Snyk should inspect for package information.
    required: true
  service:
    description: |-
      The service name.
    required: true
  version:
    description: |-
      The version of the application.
    required: true
  datadog-api-key:
    description: |-
      Datadog API Key.
    required: true
  datadog-app-key:
    description: |-
      Datadog Application Key.
    required: true
  datadog-site:
    description: |-
      The Datadog site, set to 'datadoghq.com' by default. Needs to be set to 'datadoghq.eu' for Datadog EU users.
    required: false
    default: datadoghq.com
  snyk-token:
    description: |-
      The Snyk token used to run the snyk test command.
    required: true

runs:
  using: "composite"
  steps:
  - name: Install Snyk CLI tools
    run: npm install -g snyk
    shell: bash
  - name: Install Datadog-ci
    run: npm install -g --save-dev @datadog/datadog-ci
    shell: bash
  - name: Compute dependency graph
    run: ${{ github.action_path }}/snyk-test.sh "${{ inputs.file }}" # TODO: Update with the path from the github action repository
    shell: bash
    env:
      SNYK_TOKEN: ${{ inputs.snyk-token }}
  - name: Upload dependency graph
    run: datadog-ci dependencies upload ./deps.json --source snyk --service ${{ inputs.service }} --release-version ${{ inputs.version }}
    shell: bash
    env:
      DATADOG_API_KEY: ${{ inputs.datadog-api-key }}
      DATADOG_APP_KEY: ${{ inputs.datadog-app-key }}
      DATADOG_SITE: ${{ inputs.datadog-site }}
